// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApzGiCwX8CqXdPgmxPrdedu9WDKFR1G70',
    appId: '1:974765527307:web:e610df03acd44c94a3d20e',
    messagingSenderId: '974765527307',
    projectId: 'futzada-fc3bf',
    authDomain: 'futzada-fc3bf.firebaseapp.com',
    storageBucket: 'futzada-fc3bf.appspot.com',
    measurementId: 'G-GXZKSHKZMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDiYFNqsBArubvC7WZYGwIFaHrnjbSIw',
    appId: '1:974765527307:android:30eff61f9a0dd65ca3d20e',
    messagingSenderId: '974765527307',
    projectId: 'futzada-fc3bf',
    storageBucket: 'futzada-fc3bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6hAEOFK-Vix-iKroB5R1vKCGWULR40zk',
    appId: '1:974765527307:ios:c257b57c73ad6116a3d20e',
    messagingSenderId: '974765527307',
    projectId: 'futzada-fc3bf',
    storageBucket: 'futzada-fc3bf.appspot.com',
    androidClientId: '974765527307-kkdmste80t4bd8fcmub78k6ia9t5lgap.apps.googleusercontent.com',
    iosClientId: '974765527307-m0bsqal4dgdef22lrhtafeoomhpigh6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.futzada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6hAEOFK-Vix-iKroB5R1vKCGWULR40zk',
    appId: '1:974765527307:ios:c257b57c73ad6116a3d20e',
    messagingSenderId: '974765527307',
    projectId: 'futzada-fc3bf',
    storageBucket: 'futzada-fc3bf.appspot.com',
    androidClientId: '974765527307-kkdmste80t4bd8fcmub78k6ia9t5lgap.apps.googleusercontent.com',
    iosClientId: '974765527307-m0bsqal4dgdef22lrhtafeoomhpigh6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.futzada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApzGiCwX8CqXdPgmxPrdedu9WDKFR1G70',
    appId: '1:974765527307:web:aa7f88ddbdf0c6f5a3d20e',
    messagingSenderId: '974765527307',
    projectId: 'futzada-fc3bf',
    authDomain: 'futzada-fc3bf.firebaseapp.com',
    storageBucket: 'futzada-fc3bf.appspot.com',
    measurementId: 'G-C4DP23ZFP0',
  );
}
